### ISSUE TITLE
Wire up contact form API

### ISSUE THREAD

**Issue by jtorreggiani** [specollective/spec-frontend#102]
We should be able to follow this tutorial to implement this [tutorial](https://javascript.plainenglish.io/sending-emails-with-nodemailer-in-next-js-ccada06abfc9).

### Tasks
- [X] Add environment variables to production environment
- [x] Install node-mailer package
- [x] Implement API end point to send email
- [x] Implement happy path with all parameters passed
- [x] Implement error handling
- [ ] Rejects requests from other domains
- [ ] Implement corresponding tests for all scenarios

### Relevant files
- `pages/api/contact.ts`
- `__tests__/pages/api/contact.js`
- `package.json`

### Environment variables
- `NODE_MAILER_EMAIL`
- `NODE_MAILER_PASSWORD`
- `CONTACT_EMAIL`
